### ISSUE TITLE
[ENH] ✨ Add information Bubble on idep

### ISSUE THREAD

**Issue by mehdimaaref7** [InseeFr/sugoi-ui#377]
For UI/UX purposes, we need the application to be as clear as possible for our users, therefore in the detailsApplication Page; we need  to add an information window or bubble. It will display the main informations about the idep (first_name, last_name, mail, phone, ...) instantly when you hover the idep.

**Comment by Donatien26** [comment]
i let pierrick try to do this pr seen that it's a good first issue :)
